### ISSUE TITLE
JS exception

### ISSUE THREAD

**Issue by peterzen** [decred/decrediton#1025]
On node v8/Linux

`yarn && yarn build` 
 `yarn start`

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
    at TypeError (native)
    at Event.set (/home/peter/work/decrediton/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:227:22)
    at EventEmitter.<anonymous> (/home/peter/work/decrediton/app/main.development.js:271:3)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/home/peter/work/decrediton/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by matheusd** [comment]
Sent a PR to try and fix this. If you can, please try it out and see if it solves for you.

The problem is that on `env=production`, the app tries to load from the electron `resources` dir, which doesn't really exist in development. So I added a new command line arg to specify the binaries dir and changed `yarn start` to use it.

As I understand it, `yarn start` is supposed to be used to simulate a production run on a development machine, so this should be fine.

**Comment by peterzen** [comment]
It did fix it, thank you @matheusd .
