### ISSUE TITLE
nodejs version: Unable to use `yarn dev` with nodejs v13.13.0

### ISSUE THREAD

**Issue by JoeGruffins** [decred/decrediton#2470]
nodejs v13.12.0 works fine, but with v13.13.0 I get the following error when running the command `yarn dev`:

```
[joe@hyrule decrediton]$ yarn dev
yarn run v1.22.4
$ npm run hot-server -- --start-hot
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1587622459185-0.3884170523506463/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> decrediton@1.6.0-pre hot-server /home/joe/git/decrediton
> cross-env NODE_ENV=development node --max_old_space_size=4096 -r @babel/register server.js "--start-hot"

internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/joe/git/decrediton/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/joe/git/decrediton/node_modules/@babel/preset-env/lib/index.js
- /home/joe/git/decrediton/node_modules/@babel/core/lib/config/files/plugins.js
- /home/joe/git/decrediton/node_modules/@babel/core/lib/config/files/index.js
- /home/joe/git/decrediton/node_modules/@babel/core/lib/index.js
- /home/joe/git/decrediton/node_modules/@babel/register/lib/cache.js
- /home/joe/git/decrediton/node_modules/@babel/register/lib/node.js
- /home/joe/git/decrediton/node_modules/@babel/register/lib/index.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/joe/git/decrediton/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Module._compile (/home/joe/git/decrediton/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.newLoader [as .js] (/home/joe/git/decrediton/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:972:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/joe/git/decrediton/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/home/joe/git/decrediton/node_modules/@babel/preset-env/lib/index.js',
    '/home/joe/git/decrediton/node_modules/@babel/core/lib/config/files/plugins.js',
    '/home/joe/git/decrediton/node_modules/@babel/core/lib/config/files/index.js',
    '/home/joe/git/decrediton/node_modules/@babel/core/lib/index.js',
    '/home/joe/git/decrediton/node_modules/@babel/register/lib/cache.js',
    '/home/joe/git/decrediton/node_modules/@babel/register/lib/node.js',
    '/home/joe/git/decrediton/node_modules/@babel/register/lib/index.js',
    'internal/preload'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! decrediton@1.6.0-pre hot-server: `cross-env NODE_ENV=development node --max_old_space_size=4096 -r @babel/register server.js "--start-hot"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the decrediton@1.6.0-pre hot-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/joe/.npm/_logs/2020-04-23T06_14_19_981Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Running `npm update` does solve this issue.

**Comment by amassarwi** [comment]
@JoeGruffins: Could you please try the following:
1. `rm -rf node_modules && rm yarn.lock && yarn cache clean`
2. `yarn install`
3. `yarn dev-nosandbox`

Also, you should use only `yarn` commands, we  don't use `npm` in our FE code bases AFAIK.

**Comment by JoeGruffins** [comment]
Removing yarn.lock indeed does work but looks to have exactly the same effect as `npm update`. Which is to say, the committed yarn.lock file was changed. The other suggestions did not work. I found this problem with a clean install.

**Comment by amassarwi** [comment]
Yep, that explains the *issue*, with fresh install: `deleting yarn.lock` = running `yarn` = `npm update` (in projects using npm) - and all of these have the same effect - upgrade the packages to run with your current node version.
So, with clean install & node `v13.13.0` if you go `yarn` which means packages upgrade, it works, this mean that if we want to run decrediton with node `v13.13.0` we need to upgrade the packages.

**Comment by JoeGruffins** [comment]
Ok. The readme says `Node: 10.2+` but if this is not an issue please close.

**Comment by amassarwi** [comment]
I don't mind keeping it open.
Actually there was packages change lately here: https://github.com/decred/decrediton/pull/2460, do you have the changes of that commit as well ? 
If you are running latest and the issue is still there, then we should keep this issue open and close it after the next deps upgrade which should resolve it.

**Comment by JoeGruffins** [comment]
#2460 has solved this issue for me.
