### ISSUE TITLE
refresh on launch screen crashes decrediton

### ISSUE THREAD

**Issue by vctt94** [decred/decrediton#3228]
If we are for example at the wallet selection screen and try to refresh, decrediton will crash with the message:

```
Error: Failed to serialize arguments
    at WebContents.send (electron/js2c/browser_init.js:173:2149)
    at click (/home/vctt/projects/decred/decrediton/app/main_dev/templates.js:152:34)
    at MenuItem.click (electron/js2c/browser_init.js:65:1624)
    at Function.executeCommand (electron/js2c/browser_init.js:73:1102)

**Comment by guilhermemntt** [comment]
It looks like a recent change in Electron 9 API. I'll check this out.
