### ISSUE TITLE
Library not found: /tmp/.mount_decredDX71ju/modules/dex/libdexc/libdexc.so - decrediton-v1.8.1

### ISSUE THREAD

**Issue by jaglima** [decred/decrediton#3934]
I having the following error when starting the decrediton v1.8.1 wallet on my Ubuntu. The 1.8.0 version runs smoothly. Any guess?
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Library not found: /tmp/.mount_decredDX71ju/modules/dex/libdexc/libdexc.so
    at t.getNativeFunction (/tmp/.mount_decredDX71ju/resources/app.asar/main.js:8:376055)
    at K (/tmp/.mount_decredDX71ju/resources/app.asar/main.js:2:151898)
    at Z (/tmp/.mount_decredDX71ju/resources/app.asar/main.js:2:152429)
    at 81015 (/tmp/.mount_decredDX71ju/resources/app.asar/main.js:2:113850)
    at __webpack_require__ (/tmp/.mount_decredDX71ju/resources/app.asar/main.js:8:1562687)
    at /tmp/.mount_decredDX71ju/resources/app.asar/main.js:8:1562950
    at Object.<anonymous> (/tmp/.mount_decredDX71ju/resources/app.asar/main.js:8:1562978)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

**Comment by alexlyp** [comment]
I believe some others have reported similar issues with 1.8.1 on Ubuntu.  We should be getting a fresh release out in the near future.  In the meantime you should be able to downgrade to 1.8.0 without too much of an issue.
